package instana

// Data source specific constants for alerting channel
const (
	// AlertingChannelDataSourceFieldID constant for the ID field
	AlertingChannelDataSourceFieldID = "id"

	// Description constants for data source
	AlertingChannelDescDataSource                                          = "Data source for an Instana alerting channel. Alerting channels are used to send notifications when alerts are triggered."
	AlertingChannelDescID                                                  = "The ID of the alerting channel."
	AlertingChannelDescName                                                = "The name of the alerting channel."
	AlertingChannelDescEmail                                               = "The configuration of the Email channel"
	AlertingChannelDescEmailEmails                                         = "The list of emails of the Email alerting channel"
	AlertingChannelDescOpsGenie                                            = "The configuration of the Ops Genie channel"
	AlertingChannelDescOpsGenieAPIKey                                      = "The OpsGenie API Key of the OpsGenie alerting channel"
	AlertingChannelDescOpsGenieTags                                        = "The OpsGenie tags of the OpsGenie alerting channel"
	AlertingChannelDescOpsGenieRegion                                      = "The OpsGenie region of the OpsGenie alerting channel"
	AlertingChannelDescPagerDuty                                           = "The configuration of the Pager Duty channel"
	AlertingChannelDescPagerDutyServiceIntegrationKey                      = "The Service Integration Key of the PagerDuty alerting channel"
	AlertingChannelDescSlack                                               = "The configuration of the Slack channel"
	AlertingChannelDescSlackWebhookURL                                     = "The webhook URL of the Slack alerting channel"
	AlertingChannelDescSlackIconURL                                        = "The icon URL of the Slack alerting channel"
	AlertingChannelDescSlackChannel                                        = "The Slack channel of the Slack alerting channel"
	AlertingChannelDescSplunk                                              = "The configuration of the Splunk channel"
	AlertingChannelDescSplunkURL                                           = "The URL of the Splunk alerting channel"
	AlertingChannelDescSplunkToken                                         = "The token of the Splunk alerting channel"
	AlertingChannelDescVictorOps                                           = "The configuration of the VictorOps channel"
	AlertingChannelDescVictorOpsAPIKey                                     = "The API Key of the VictorOps alerting channel"
	AlertingChannelDescVictorOpsRoutingKey                                 = "The Routing Key of the VictorOps alerting channel"
	AlertingChannelDescWebhook                                             = "The configuration of the Webhook channel"
	AlertingChannelDescWebhookWebhookURLs                                  = "The list of webhook urls of the Webhook alerting channel"
	AlertingChannelDescWebhookHTTPHeaders                                  = "The optional map of HTTP headers of the Webhook alerting channel"
	AlertingChannelDescOffice365                                           = "The configuration of the Office 365 channel"
	AlertingChannelDescOffice365WebhookURL                                 = "The webhook URL of the Office 365 alerting channel"
	AlertingChannelDescGoogleChat                                          = "The configuration of the Google Chat channel"
	AlertingChannelDescGoogleChatWebhookURL                                = "The webhook URL of the Google Chat alerting channel"
	AlertingChannelDescServiceNow                                          = "The configuration of the ServiceNow channel"
	AlertingChannelDescServiceNowURL                                       = "The ServiceNow URL of the ServiceNow alerting channel"
	AlertingChannelDescServiceNowUsername                                  = "The username of the ServiceNow alerting channel"
	AlertingChannelDescServiceNowPassword                                  = "The password of the ServiceNow alerting channel"
	AlertingChannelDescServiceNowAutoCloseIncidents                        = "Whether to automatically close incidents when alerts are resolved"
	AlertingChannelDescServiceNowApplication                               = "The configuration of the ServiceNow ITSM (Enhanced) channel"
	AlertingChannelDescServiceNowApplicationURL                            = "The ServiceNow URL of the ServiceNow ITSM (Enhanced) alerting channel"
	AlertingChannelDescServiceNowApplicationUsername                       = "The username of the ServiceNow ITSM (Enhanced) alerting channel"
	AlertingChannelDescServiceNowApplicationPassword                       = "The password of the ServiceNow ITSM (Enhanced) alerting channel"
	AlertingChannelDescServiceNowApplicationTenant                         = "The tenant of the ServiceNow ITSM (Enhanced) alerting channel"
	AlertingChannelDescServiceNowApplicationUnit                           = "The unit of the ServiceNow ITSM (Enhanced) alerting channel"
	AlertingChannelDescServiceNowApplicationInstanaURL                     = "The Instana URL of the ServiceNow ITSM (Enhanced) alerting channel"
	AlertingChannelDescServiceNowApplicationEnableSendInstanaNotes         = "Whether to enable sending Instana notes"
	AlertingChannelDescServiceNowApplicationEnableSendServiceNowActivities = "Whether to enable sending ServiceNow activities"
	AlertingChannelDescServiceNowApplicationEnableSendServiceNowWorkNotes  = "Whether to enable sending ServiceNow work notes"
	AlertingChannelDescServiceNowApplicationManuallyClosedIncidents        = "Whether incidents are manually closed"
	AlertingChannelDescServiceNowApplicationResolutionOfIncident           = "The resolution of incident"
	AlertingChannelDescServiceNowApplicationSnowStatusOnCloseEvent         = "The ServiceNow status on close event"
	AlertingChannelDescPrometheusWebhook                                   = "The configuration of the Prometheus Webhook channel"
	AlertingChannelDescPrometheusWebhookWebhookURL                         = "The webhook URL of the Prometheus Webhook alerting channel"
	AlertingChannelDescPrometheusWebhookReceiver                           = "The receiver of the Prometheus Webhook alerting channel"
	AlertingChannelDescWebexTeamsWebhook                                   = "The configuration of the Webex Teams Webhook channel"
	AlertingChannelDescWebexTeamsWebhookWebhookURL                         = "The webhook URL of the Webex Teams Webhook alerting channel"
	AlertingChannelDescWatsonAIOpsWebhook                                  = "The configuration of the IBM Cloud Pack (Watson AIOps) Webhook channel"
	AlertingChannelDescWatsonAIOpsWebhookWebhookURL                        = "The webhook URL of the IBM Cloud Pack (Watson AIOps) Webhook alerting channel"
	AlertingChannelDescWatsonAIOpsWebhookHTTPHeaders                       = "The list of HTTP headers for the IBM Cloud Pack (Watson AIOps) Webhook alerting channel"

	// Error message constants
	AlertingChannelErrUnexpectedConfigureType = "Unexpected Data Source Configure Type"
	AlertingChannelErrReadingChannels         = "Error reading alerting channels"
	AlertingChannelErrChannelNotFound         = "Alerting channel not found"
	AlertingChannelErrUnsupportedChannelType  = "Unsupported alerting channel type"
)

// Made with Bob
