// Code generated by MockGen. DO NOT EDIT.
// Source: instana/restapi/Instana-api.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	instana "github.com/instana/instana-go-client/instana"
	"github.com/instana/instana-go-client/shared/rest"
	gomock "go.uber.org/mock/gomock"
)

// MockInstanaAPI is a mock of InstanaAPI interface.
type MockInstanaAPI struct {
	ctrl     *gomock.Controller
	recorder *MockInstanaAPIMockRecorder
}

// MockInstanaAPIMockRecorder is the mock recorder for MockInstanaAPI.
type MockInstanaAPIMockRecorder struct {
	mock *MockInstanaAPI
}

// NewMockInstanaAPI creates a new mock instance.
func NewMockInstanaAPI(ctrl *gomock.Controller) *MockInstanaAPI {
	mock := &MockInstanaAPI{ctrl: ctrl}
	mock.recorder = &MockInstanaAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanaAPI) EXPECT() *MockInstanaAPIMockRecorder {
	return m.recorder
}

// APITokens mocks base method.
func (m *MockInstanaAPI) APITokens() rest.RestResource[*instana.APIToken] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APITokens")
	ret0, _ := ret[0].(rest.RestResource[*instana.APIToken])
	return ret0
}

// APITokens indicates an expected call of APITokens.
func (mr *MockInstanaAPIMockRecorder) APITokens() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APITokens", reflect.TypeOf((*MockInstanaAPI)(nil).APITokens))
}

// AlertingChannels mocks base method.
func (m *MockInstanaAPI) AlertingChannels() rest.RestResource[*instana.AlertingChannel] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertingChannels")
	ret0, _ := ret[0].(rest.RestResource[*instana.AlertingChannel])
	return ret0
}

// AlertingChannels indicates an expected call of AlertingChannels.
func (mr *MockInstanaAPIMockRecorder) AlertingChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertingChannels", reflect.TypeOf((*MockInstanaAPI)(nil).AlertingChannels))
}

// AlertingConfigurations mocks base method.
func (m *MockInstanaAPI) AlertingConfigurations() rest.RestResource[*instana.AlertingConfiguration] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertingConfigurations")
	ret0, _ := ret[0].(rest.RestResource[*instana.AlertingConfiguration])
	return ret0
}

// AlertingConfigurations indicates an expected call of AlertingConfigurations.
func (mr *MockInstanaAPIMockRecorder) AlertingConfigurations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertingConfigurations", reflect.TypeOf((*MockInstanaAPI)(nil).AlertingConfigurations))
}

// ApplicationAlertConfigs mocks base method.
func (m *MockInstanaAPI) ApplicationAlertConfigs() rest.RestResource[*instana.ApplicationAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplicationAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*instana.ApplicationAlertConfig])
	return ret0
}

// ApplicationAlertConfigs indicates an expected call of ApplicationAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) ApplicationAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplicationAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).ApplicationAlertConfigs))
}

// ApplicationConfigs mocks base method.
func (m *MockInstanaAPI) ApplicationConfigs() rest.RestResource[*instana.ApplicationConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplicationConfigs")
	ret0, _ := ret[0].(rest.RestResource[*instana.ApplicationConfig])
	return ret0
}

// ApplicationConfigs indicates an expected call of ApplicationConfigs.
func (mr *MockInstanaAPIMockRecorder) ApplicationConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplicationConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).ApplicationConfigs))
}

// BuiltinEventSpecifications mocks base method.
func (m *MockInstanaAPI) BuiltinEventSpecifications() instana.ReadOnlyRestResource[*instana.BuiltinEventSpecification] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuiltinEventSpecifications")
	ret0, _ := ret[0].(instana.ReadOnlyRestResource[*instana.BuiltinEventSpecification])
	return ret0
}

// BuiltinEventSpecifications indicates an expected call of BuiltinEventSpecifications.
func (mr *MockInstanaAPIMockRecorder) BuiltinEventSpecifications() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuiltinEventSpecifications", reflect.TypeOf((*MockInstanaAPI)(nil).BuiltinEventSpecifications))
}

// CustomDashboards mocks base method.
func (m *MockInstanaAPI) CustomDashboards() rest.RestResource[*instana.CustomDashboard] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomDashboards")
	ret0, _ := ret[0].(rest.RestResource[*instana.CustomDashboard])
	return ret0
}

// CustomDashboards indicates an expected call of CustomDashboards.
func (mr *MockInstanaAPIMockRecorder) CustomDashboards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomDashboards", reflect.TypeOf((*MockInstanaAPI)(nil).CustomDashboards))
}

// CustomEventSpecifications mocks base method.
func (m *MockInstanaAPI) CustomEventSpecifications() rest.RestResource[*instana.CustomEventSpecification] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomEventSpecifications")
	ret0, _ := ret[0].(rest.RestResource[*instana.CustomEventSpecification])
	return ret0
}

// CustomEventSpecifications indicates an expected call of CustomEventSpecifications.
func (mr *MockInstanaAPIMockRecorder) CustomEventSpecifications() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomEventSpecifications", reflect.TypeOf((*MockInstanaAPI)(nil).CustomEventSpecifications))
}

// GlobalApplicationAlertConfigs mocks base method.
func (m *MockInstanaAPI) GlobalApplicationAlertConfigs() rest.RestResource[*instana.ApplicationAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalApplicationAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*instana.ApplicationAlertConfig])
	return ret0
}

// GlobalApplicationAlertConfigs indicates an expected call of GlobalApplicationAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) GlobalApplicationAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalApplicationAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).GlobalApplicationAlertConfigs))
}

// Groups mocks base method.
func (m *MockInstanaAPI) Groups() rest.RestResource[*instana.Group] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Groups")
	ret0, _ := ret[0].(rest.RestResource[*instana.Group])
	return ret0
}

// Groups indicates an expected call of Groups.
func (mr *MockInstanaAPIMockRecorder) Groups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Groups", reflect.TypeOf((*MockInstanaAPI)(nil).Groups))
}

// SliConfigs mocks base method.
func (m *MockInstanaAPI) SliConfigs() rest.RestResource[*instana.SliConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SliConfigs")
	ret0, _ := ret[0].(rest.RestResource[*instana.SliConfig])
	return ret0
}

// SliConfigs indicates an expected call of SliConfigs.
func (mr *MockInstanaAPIMockRecorder) SliConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SliConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).SliConfigs))
}

// SloConfigs mocks base method.
func (m *MockInstanaAPI) SloConfigs() rest.RestResource[*instana.SloConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SloConfigs")
	ret0, _ := ret[0].(rest.RestResource[*instana.SloConfig])
	return ret0
}

// SloConfigs indicates an expected call of SloConfigs.
func (mr *MockInstanaAPIMockRecorder) SloConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SloConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).SloConfigs))
}

// SloAlertConfig mocks base method.
func (m *MockInstanaAPI) SloAlertConfig() rest.RestResource[*instana.SloAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SloAlertConfig")
	ret0, _ := ret[0].(rest.RestResource[*instana.SloAlertConfig])
	return ret0
}

// SloAlertConfig indicates an expected call of SloConfigs.
func (mr *MockInstanaAPIMockRecorder) SloAlertConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SloAlertConfig", reflect.TypeOf((*MockInstanaAPI)(nil).SloAlertConfig))
}

// SloCorrectionConfig mocks base method.
func (m *MockInstanaAPI) SloCorrectionConfig() rest.RestResource[*instana.SloCorrectionConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SloCorrectionConfig")
	ret0, _ := ret[0].(rest.RestResource[*instana.SloCorrectionConfig])
	return ret0
}

// SloCorrectionConfig indicates an expected call of SloCorrectionConfig.
func (mr *MockInstanaAPIMockRecorder) SloCorrectionConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SloCorrectionConfig", reflect.TypeOf((*MockInstanaAPI)(nil).SloCorrectionConfig()))
}

// SyntheticLocation mocks base method.
func (m *MockInstanaAPI) SyntheticLocation() instana.ReadOnlyRestResource[*instana.SyntheticLocation] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyntheticLocation")
	ret0, _ := ret[0].(instana.ReadOnlyRestResource[*instana.SyntheticLocation])
	return ret0
}

// SyntheticLocation indicates an expected call of SyntheticLocation.
func (mr *MockInstanaAPIMockRecorder) SyntheticLocation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyntheticLocation", reflect.TypeOf((*MockInstanaAPI)(nil).SyntheticLocation))
}

// SyntheticTest mocks base method.
func (m *MockInstanaAPI) SyntheticTest() rest.RestResource[*instana.SyntheticTest] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyntheticTest")
	ret0, _ := ret[0].(rest.RestResource[*instana.SyntheticTest])
	return ret0
}

// SyntheticTest indicates an expected call of SyntheticTest.
func (mr *MockInstanaAPIMockRecorder) SyntheticTest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyntheticTest", reflect.TypeOf((*MockInstanaAPI)(nil).SyntheticTest))
}

// WebsiteAlertConfig mocks base method.
func (m *MockInstanaAPI) WebsiteAlertConfig() rest.RestResource[*instana.WebsiteAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebsiteAlertConfig")
	ret0, _ := ret[0].(rest.RestResource[*instana.WebsiteAlertConfig])
	return ret0
}

// WebsiteAlertConfig indicates an expected call of WebsiteAlertConfig.
func (mr *MockInstanaAPIMockRecorder) WebsiteAlertConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebsiteAlertConfig", reflect.TypeOf((*MockInstanaAPI)(nil).WebsiteAlertConfig))
}

// MobileAlertConfig mocks base method.
func (m *MockInstanaAPI) MobileAlertConfig() rest.RestResource[*instana.MobileAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MobileAlertConfig")
	ret0, _ := ret[0].(rest.RestResource[*instana.MobileAlertConfig])
	return ret0
}

// MobileAlertConfig indicates an expected call of MobileAlertConfig.
func (mr *MockInstanaAPIMockRecorder) MobileAlertConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MobileAlertConfig", reflect.TypeOf((*MockInstanaAPI)(nil).MobileAlertConfig))
}

// WebsiteMonitoringConfig mocks base method.
func (m *MockInstanaAPI) WebsiteMonitoringConfig() rest.RestResource[*instana.WebsiteMonitoringConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebsiteMonitoringConfig")
	ret0, _ := ret[0].(rest.RestResource[*instana.WebsiteMonitoringConfig])
	return ret0
}

// WebsiteMonitoringConfig indicates an expected call of WebsiteMonitoringConfig.
func (mr *MockInstanaAPIMockRecorder) WebsiteMonitoringConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebsiteMonitoringConfig", reflect.TypeOf((*MockInstanaAPI)(nil).WebsiteMonitoringConfig))
}

func (m *MockInstanaAPI) InfraAlertConfig() rest.RestResource[*instana.InfraAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfraAlertConfig")
	ret0, _ := ret[0].(rest.RestResource[*instana.InfraAlertConfig])
	return ret0
}

// AutomationActions mocks base method.
func (m *MockInstanaAPI) AutomationActions() rest.RestResource[*instana.AutomationAction] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutomationAction")
	ret0, _ := ret[0].(rest.RestResource[*instana.AutomationAction])
	return ret0
}

// AutomationPolicies mocks base method.
func (m *MockInstanaAPI) AutomationPolicies() rest.RestResource[*instana.AutomationPolicy] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutomationPolicy")
	ret0, _ := ret[0].(rest.RestResource[*instana.AutomationPolicy])
	return ret0
}

// HostAgents mocks base method.
func (m *MockInstanaAPI) HostAgents() instana.ReadOnlyRestResource[*instana.HostAgent] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HostAgent")
	ret0, _ := ret[0].(instana.ReadOnlyRestResource[*instana.HostAgent])
	return ret0
}

// AutomationActions indicates an expected call of AutomationActions.
func (mr *MockInstanaAPIMockRecorder) AutomationActions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutomationAction", reflect.TypeOf((*MockInstanaAPI)(nil).AutomationActions))
}

// AutomationPolicies indicates an expected call of AutomationPolicies.
func (mr *MockInstanaAPIMockRecorder) AutomationPolicies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutomationPolicy", reflect.TypeOf((*MockInstanaAPI)(nil).AutomationPolicies))
}

// HostAgents indicates an expected call of AutomationPolicies.
func (mr *MockInstanaAPIMockRecorder) HostAgents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HostAgent", reflect.TypeOf((*MockInstanaAPI)(nil).HostAgents))
}

// LogAlertConfig mocks base method.
func (m *MockInstanaAPI) LogAlertConfig() rest.RestResource[*instana.LogAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAlertConfig")
	ret0, _ := ret[0].(rest.RestResource[*instana.LogAlertConfig])
	return ret0
}

// LogAlertConfig indicates an expected call of LogAlertConfig.
func (mr *MockInstanaAPIMockRecorder) LogAlertConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAlertConfig", reflect.TypeOf((*MockInstanaAPI)(nil).LogAlertConfig))
}

// Teams mocks base method.
func (m *MockInstanaAPI) Teams() rest.RestResource[*instana.Team] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Teams")
	ret0, _ := ret[0].(rest.RestResource[*instana.Team])
	return ret0
}

// Teams indicates an expected call of Teams.
func (mr *MockInstanaAPIMockRecorder) Teams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Teams", reflect.TypeOf((*MockInstanaAPI)(nil).Teams))
}

// Roles mocks base method.
func (m *MockInstanaAPI) Roles() rest.RestResource[*instana.Role] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Roles")
	ret0, _ := ret[0].(rest.RestResource[*instana.Role])
	return ret0
}

// Roles indicates an expected call of Roles.
func (mr *MockInstanaAPIMockRecorder) Roles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Roles", reflect.TypeOf((*MockInstanaAPI)(nil).Roles))
}

// Users mocks base method.
func (m *MockInstanaAPI) Users() instana.ReadOnlyRestResource[*instana.User] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(instana.ReadOnlyRestResource[*instana.User])
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockInstanaAPIMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockInstanaAPI)(nil).Users))
}

// SyntheticAlertConfigs mocks base method.
func (m *MockInstanaAPI) SyntheticAlertConfigs() rest.RestResource[*instana.SyntheticAlertConfig] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyntheticAlertConfigs")
	ret0, _ := ret[0].(rest.RestResource[*instana.SyntheticAlertConfig])
	return ret0
}

// SyntheticAlertConfigs indicates an expected call of SyntheticAlertConfigs.
func (mr *MockInstanaAPIMockRecorder) SyntheticAlertConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyntheticAlertConfigs", reflect.TypeOf((*MockInstanaAPI)(nil).SyntheticAlertConfigs))
}
